name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
          
      - name: Install Dependencies
        run: |
          npm init --yes
          npm install
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
          
      - name: Build and Publish
        run: msbuild /t:Publish /p:Configuration=Release
      
