name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Dependencies
        run: |
          npm init --yes
          npm install
        
      - name: Build and Publish
        run: dotnet publish -c Release -o ./publish
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'