name: Deploy to AWS 

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
          
      - name: Setup npm install
        run: npm install
          
      - name: Build and unit testing
        run: |
          npm run build
          npm test -- --runInBand
